### ISSUE TITLE
Semantische volgorde

### ISSUE THREAD

**Issue by koeenm** [lisavanmansom/the-startup-website-bnr#1]
Ik begrijp de structuur van de html, en het is duidelijk waar verschillende onderdelen van de site zijn door gebruik van articles.

Het enige echt aan te merken is dat je van een h2 naar een h4 overspringt, terwijl je beter in plaats van die h4 een h3 kan maken, voor de volgorde van de website

**Comment by lisavanmansom** [comment]
Yes dankjewel! ik heb wat semantischer gemaakt
