### ISSUE TITLE
JS kan vervangen worden door CSS

### ISSUE THREAD

**Issue by Jesse-Kramer** [lisavanmansom/the-startup-website-bnr#10]
Je kan deze functie vervangen door in je css de :hover atribuut te gebruiken. Hierdoor heb je een heel stuk JS code niet nodig.

https://github.com/lisavanmansom/the-startup-website-bnr/blob/8c4ee9b4d99b65a178bcde95ac7f45a43126a15f/script.js#L34-L38

Meer informatie is hier te vinden:
https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

**Comment by lisavanmansom** [comment]
Yes dankjewel! Ik heb het aangepast
<img width="1046" alt="Scherm­afbeelding 2024-01-22 om 11 36 50" src="https://github.com/lisavanmansom/the-startup-website-bnr/assets/144007419/495dbf4a-926f-44ce-976c-f8dd7706a37a">
