### ISSUE TITLE
Je lijkt hier een element te gebruiken dat niet in html mag

### ISSUE THREAD

**Issue by Patrickkhr** [lisavanmansom/the-startup-website-bnr#13]
https://github.com/lisavanmansom/the-startup-website-bnr/blob/8c4ee9b4d99b65a178bcde95ac7f45a43126a15f/index.html#L164

Je lijkt hier een element te gebruiken dat niet in html mag

Volgens mij doet dit element nu ook niks dus kan je gewoon weghalen

bron: <img width="1330" alt="image" src="https://github.com/lisavanmansom/the-startup-website-bnr/assets/143999685/5e8751f4-d3ee-448c-aa1f-d43b1722539d">

**Comment by lisavanmansom** [comment]
Yes dankjewel voor je issue! Ik heb het aangepast

https://github.com/lisavanmansom/the-startup-website-bnr/commit/b0c179ea582025ff87db6a6ca18de156905f0387
