### ISSUE TITLE
Inspringen bij nesten.

### ISSUE THREAD

**Issue by TygoWolven** [lisavanmansom/the-startup-website-bnr#3]
**Tip:**
Ik zie in de HTML van je app-landingspagina dat je op verschillende manieren elementen nest, en laat inspringen. Neem bijvoorbeeld deze eerste unordered-list. Hier zet je de link direct binnen in de list-item, op dezelfde regel. Terwijl je bij een andere unordered-list (de tweede) hier enters voor gebruikt. Waardoor je in plaats van 1 regel, 3 regels gebruikt. Ik denk dat het beter zou zijn als je consistent dezelfde manier toepast voor je gehele pagina. Zo behoud je meer overzicht over wat er allemaal in je pagina staat.

https://github.com/lisavanmansom/the-startup-website-bnr/blob/811ab670ae15e7ee26242d47f386e5fdb3925efc/app-landing-page.html#L33-L37

https://github.com/lisavanmansom/the-startup-website-bnr/blob/811ab670ae15e7ee26242d47f386e5fdb3925efc/app-landing-page.html#L77-L86

**Top:**
Verder vind ik dat je HTML mooi geschreven is. Je maakt gebruik van de juiste elementen, die voor de juiste functie dienen. En je zet overal mooie comments bij zodat het voor iedere lezer duidelijk is waar de code voor bedoeld is.

**Comment by lisavanmansom** [comment]
Dankjewel ik heb het aangepast!

https://github.com/lisavanmansom/the-startup-website-bnr/blob/6789502c5451b0b7cda7db9702e892ffcbb33a02/app-landing-page.html#L47-L79
