### ISSUE TITLE
Het knopje meer info

### ISSUE THREAD

**Issue by Pink-Mallow** [lisavanmansom/the-startup-website-bnr#5]
Je code ziet er netjes uit, maar op de website zelf:
![image](https://github.com/lisavanmansom/the-startup-website-bnr/assets/144671961/5b6de0ab-1d9f-49b0-9430-9bdf44ffbcf2)
Probeer de meer info tekst in het midden te zetten. Of maak de box zelf kleiner.
Het is een kleine detail maar ik keek er telkens naar terug.

**Comment by lisavanmansom** [comment]
Yes dankjewel! Ik heb het aangepast
<img width="416" alt="Scherm­afbeelding 2024-01-17 om 12 51 40" src="https://github.com/lisavanmansom/the-startup-website-bnr/assets/144007419/bc9b69ce-435a-4330-bb03-bec74afa7224">
