### ISSUE TITLE
Verkeerd afsluiten article en div

### ISSUE THREAD

**Issue by Jesse-Kramer** [lisavanmansom/the-startup-website-bnr#7]
Je sluit hier eerst een div af en daarna de article, terwijl die article in de div staat. Of kijk ik verkeerd?

https://github.com/lisavanmansom/the-startup-website-bnr/blob/8c4ee9b4d99b65a178bcde95ac7f45a43126a15f/index.html#L56-L88

**Comment by lisavanmansom** [comment]
Dankjewel! ik heb het aangepast
https://github.com/lisavanmansom/the-startup-website-bnr/blob/90e8cec5083cf6cfca3df736b92b2cc0d083d175/index.html#L54-L88
