### ISSUE TITLE
Feedforward toevoegen

### ISSUE THREAD

**Issue by saschavanvliett** [lisavanmansom/the-startup-website-bnr#9]
Bij sommige buttons heb je gebruik gemaakt van feedforward door een hover toe te voegen, maar dit heb je niet overal gedaan. Misschien handig om ook bij de andere buttons toe te voegen :)

**Comment by lisavanmansom** [comment]
Dankjewel! Ik heb het toegevoegd bij de buttons.

<img width="252" alt="Scherm­afbeelding 2024-01-20 om 14 47 25" src="https://github.com/lisavanmansom/the-startup-website-bnr/assets/144007419/8cfff1ea-ec42-4c61-a952-d8b4741d3f25">
<img width="252" alt="Scherm­afbeelding 2024-01-20 om 14 47 28" src="https://github.com/lisavanmansom/the-startup-website-bnr/assets/144007419/5f991517-299d-47e9-bf5e-ad13475cb083">
